
name: coverage

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: run coverage testing
      run: |
        docker-compose -f docker-compose.coverage.yml up

    - uses: codecov/codecov-action@v1
      with:
        #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        #file: ./coverage.xml # optional
        flags: unittests # optional
        name: mmd-unittest # optional
        fail_ci_if_error: true # optional (default = false)


